# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Grd2Stream
                                 A QGIS plugin
 TODO
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-12-14
        copyright            : (C) 2024 by TODO
        email                : scienceflightplanner@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Grd2Stream class from file Grd2Stream.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .grd_2_stream import Grd2Stream
    return Grd2Stream(iface)
