# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Grd2Stream
                                 A QGIS plugin
 TODO
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-12-14
        git sha              : $Format:%H$
        copyright            : (C) 2024 by TODO
        email                : scienceflightplanner@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from PyQt5.QtWidgets import QToolBar
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
from qgis.gui import QgisInterface

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .grd_2_stream_dialog import Grd2StreamDialog
import os.path


class Grd2Stream:
    """QGIS Plugin Implementation."""

    def __init__(self, iface: QgisInterface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.sfp_toolbar = None
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)

        # Declare instance attributes
        self.actions = []
        self.menu = u'&Grd2Stream '

        self.pluginMenu = self.iface.pluginMenu().addMenu(QIcon(":/plugins/grd_2_stream/icon.png"), "&Grd2Stream")

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar_sfp_toolbar=False,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar_sfp_toolbar:
            self.sfp_toolbar.addAction(action)
            # Adds plugin icon to Plugins toolbar
        else:
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.pluginMenu.addAction(action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""
        add_to_toolbar_sfp_toolbar = False
        self.sfp_toolbar = self.iface.mainWindow().findChild(QToolBar, "ScienceFlightPlanner")
        #for c in self.iface.mainWindow().findChildren(QToolBar, "ScienceFlightPlanner"):
         #   if isinstance(c, QToolBar):
          #      print(str(c) + c.objectName())

        print(self.sfp_toolbar)
        if not self.sfp_toolbar is None:
            add_to_toolbar_sfp_toolbar = True

        icon_path = ':/plugins/grd_2_stream/icon.png'
        self.add_action(
            icon_path,
            text=u'grd2stream Menu Item',
            callback=self.run,
            parent=self.iface.mainWindow(),
            add_to_toolbar_sfp_toolbar=add_to_toolbar_sfp_toolbar
        )


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removeToolBarIcon(action)
        self.iface.pluginMenu().removeAction(self.pluginMenu.menuAction())


    def run(self):
        """Run method that performs all the real work"""
        print("Calculate...")
